### ISSUE TITLE
Can i find the paper in the web?

### ISSUE THREAD

**Issue by ztl-35** [yoyo-yun/MA-Bert#1]
Hi, Thanks for releasing the code, but i can't find the paper in Arxiv or Google scholar. Could you please upload the paper in this repo?

**Comment by yoyo-yun** [comment]
Thank you for your question. The paper will be uploaded when it is officially published.

**Comment by drunkprogrammer** [comment]
hello, after I unzip the dataset and run it, it occurs error: 
 [Errno 2] No such file or directory: 'corpus/imdb/train_both.pt
But I don't find this file

**Comment by yoyo-yun** [comment]
> Hi, Thanks for releasing the code, but i can't find the paper in Arxiv or Google scholar. Could you please upload the paper in this repo?

**Comment by yoyo-yun** [comment]
> Hi, Thanks for releasing the code, but i can't find the paper in Arxiv or Google scholar. Could you please upload the paper in this repo?

The paper is available at https://aclanthology.org/2021.findings-acl.206/
